# -*- coding: utf-8 -*-
"""Cas_pratique

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_HwFZRcC3kKIj4qlTmaxQ6jHOGSkblsz

# Cas pratique : 

Améliorer une application visant à reconnaître si l'utilisateur porte (ou non) :
- un casque de chantier
- un gilet

# Importations et chargement des données
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt  # install

import torch
import utils
display = utils.notebook_init()  # checks

# dézipper fichier
!unzip -q /content/train_data.zip -d ../

# importation à partir d'un drive
# from google.colab import drive
# drive.mount('/content/drive')

"""# 1. Detect

`detect.py` runs YOLOv5 inference on a variety of sources, downloading models automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases), and saving results to `runs/detect`. Example inference sources are:

```shell
python detect.py --source 0  # webcam
                          img.jpg  # image 
                          vid.mp4  # video
                          screen  # screenshot
                          path/  # directory
                          'path/*.jpg'  # glob
                          'https://youtu.be/Zgi9g1ksQHc'  # YouTube
                          'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```
"""

!python detect.py --weights /content/yolov5/runs/train/exp/weights/best.pt --img 640 --conf 0.25 --source ../test/
# display.Image(filename='runs/detect/exp/zidane.jpg', width=600)

"""# 2. Validate
Validate a model's accuracy on the [COCO](https://cocodataset.org/#home) dataset's `val` or `test` splits. Models are downloaded automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases). To show results by class use the `--verbose` flag.
"""

# Validate YOLOv5s on COCO val
!python val.py --weights yolov5s.pt --data coco.yaml --img 640 --half

"""# **Train** :
---
"""

!python train.py --img 640 --batch 10 --epochs 50 --data coco_custom.yaml --weights yolov5s.pt --cache
